language: python
python:
    - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

branches:
  only:
  - master

# Install dependencies
addons:
  apt:
    packages:
      - jq

env:
    - PLATFORMIO_CI_SRC=examples/basic.ino


install:
    - pip install -U platformio

script:
  - platformio ci --lib="." --board=uno --board=megaatmega2560 --board=esp12e --board=nodemcu --board=esp32dev
  - jq . library.json

notifications:
  email:
    on_success: change
    on_failure: change
